### PR TITLE
Split FaultKind

### LINKED ISSUE #285: Split up `FaultKind`.
`FaultKind`s should form a hierarchy similar (and parallel) to errors, and live in the respective modules.

Let's create a `FaultKind` enum for each algorithm, with `SubAlgorithm(sub_algorithm::FaultKind)` variants where needed (like currently with `AckMessageFault`), and possibly with corresponding `From` impls. I think even `Fault` and `FaultLog` should be generic in the fault kind, so that if you're using `BinaryAgreement`, the compiler doesn't force you to consider `HoneyBadger` faults.

They should all implement `Display`, and print an explanation (basically what's currently the doc comment). Maybe we should derive `Fail` to make this easier?

### PR DESCRIPTION
**Pull request by phahulin**
Largely based on https://github.com/poanetwork/hbbft/pull/343
Closes #285

### CODE REVIEW

File: examples/simulation.rs [hunk 1]
```diff
@@ -439,7 +439,9 @@ fn main() {
             .build_with_transactions(txs.clone(), rng)
             .expect("instantiate QueueingHoneyBadger");
         let (sq, mut step) = SenderQueue::builder(qhb, peer_ids.into_iter()).build(our_id);
-        assert!(step.extend_with(qhb_step, Message::from).is_empty());
+        assert!(step
+            .extend_with(qhb_step, |fault| fault, Message::from)
+            .is_empty());
```
Comment (afck) [inline examples/simulation.rs]: Might be more readable to just assert that both `step` and `qhb_step` are empty. No need to `extend_with`. (Also below.)

Comment (phahulin) [reply examples/simulation.rs]: `Step.extend_with` returns its argument's `output` field, in this case that would be `qhb_step.output`, so it seems that this assertion is equivalent to `assert!(qhb_step.output.is_empty())` not to `assert!(step.is_empty() && qhb_step.is_empty())`

Is that correct or did you mean something else?

Comment (afck) [reply examples/simulation.rs]: Ah, you're right, of course, sorry! :+1:

File: src/fault_log.rs [hunk 2]
```diff
@@ -1,135 +1,78 @@
...
-    /// `BinaryAgreement` received a duplicate `Aux` message.
-    DuplicateAux,
-    /// `BinaryAgreement` received multiple `Conf` messages.
-    MultipleConf,
-    /// `BinaryAgreement` received multiple `Term` messages.
-    MultipleTerm,
-    /// `BinaryAgreement` received a message with an epoch too far ahead.
-    AgreementEpoch,
-}
+
```
Comment (afck) [inline src/fault_log.rs]: I think empty lines in doc comments should also start with `//!`.

File: src/subset/error.rs [hunk 3]
```diff
@@ -27,3 +27,14 @@ pub enum Error {
 
 /// A subset result.
 pub type Result<T> = result::Result<T, Error>;
+
+/// Subset does not actually have any messages defined, so there's no real FaultKind to define here
```
Comment (afck) [inline src/subset/error.rs]: That documentation is a bit weird. Maybe something like: "Faults that can be detected in `Subset`."
It's clear from the set of variants that these can only originate in `Broadcast` or `BinaryAgreement`.

File: src/traits.rs [hunk 4]
```diff
@@ -99,27 +109,42 @@ impl<M, O, N> Step<M, O, N> {
...
+    pub fn map<M2, O2, F2, FO, FF, FM>(
+        self,
+        f_out: FO,
+        f_fail2fail: FF,
+        f_msg: FM,
+    ) -> Step<M2, O2, N, F2>
     where
+        F2: Fail,
         FO: Fn(O) -> O2,
+        FF: Fn(Fault<N, F>) -> Fault<N, F2>,
```
Comment (afck) [inline src/traits.rs]: We should only have to specify an `Fn(F) -> F2` here: The node ID must never change in this conversion. (Also in the other methods.)

File: examples/simulation.rs (hunk 1 above)
Comment (mbr) [reply examples/simulation.rs]: I think assertions should be side-effect free! If the `assert!` macro were to be turned off, the code would break!

If this was `debug_assert!`, it would definitely be wrong, I am not 100% sure about the `assert!` macro though - but the fact that I even have to think about/research it make me prefer to have all the actual work done outside the assert.

Comment (mbr) [reply examples/simulation.rs]: And yes, I realize that this was the case even before this PR, so the question is whether or not we want to change it now in one fell swoop.

File: src/fault_log.rs [hunk 5]
```diff
@@ -1,135 +1,78 @@
...
 }
 
-impl<N> Fault<N> {
-    /// Creates a new fault, blaming `node_id` for the `kind`.
-    pub fn new(node_id: N, kind: FaultKind) -> Self {
+impl<N, F> Fault<N, F>
+where
+    F: Fail,
+{
+    /// Creates a new fault given a node ID and a fault description.
```
Comment (mbr) [inline src/fault_log.rs]: Minor, but I really liked the old docs because it made it abundantly clear what is going on (assigning blame for `kind` to `node_id`). Is there a reason to change it?

File: examples/simulation.rs (hunk 1 above)
Comment (phahulin) [reply examples/simulation.rs]: `step` is defined as `mut` in this piece of code, and `step.extend_with(...)` actually changes it's state, then `step` is returned from the closure. So it seems that in order to preserve the current functionality intact, it would be necessary to call `extend_with` anyway. In such a case we can keep the assert as it is now.
If assertion is changed to something like `assert!(step.is_empty() && qhb_step.is_empty())` the ci indeed fails.

Comment (phahulin) [reply examples/simulation.rs]: So I suggest it's not changed (at least in this PR)

Comment (afck) [reply examples/simulation.rs]: I agree, we should assign this to a local `output` variable and _then_ assert that `output.is_empty()`. But I'm fine with postponing this change to another PR, too, if you prefer.

File: src/traits.rs (hunk 4 above)
Comment (phahulin) [reply src/traits.rs]: Sorry, I don't quite know how to do this one. So the general idea is that `FF` should only work on `Fail` and return `Fail` without ability to touch node id, correct?

If I change the line here (and below it in `extend_with`) to `FF: Fn(F) -> F2`, it seems to break things in some other places (because of type mismatch). Is correcting them one by one the way to go or should I do this in a different way?

Comment (afck) [reply src/traits.rs]: Yes, I'm afraid they have to be fixed one by one, sorry. :grimacing: 
I imagine something like this:
* Add something like `fn map(self, FF) -> Fault<N, F2> where FF: Fn(F) -> F2` to `Fault<N, F>`, and similarly to `FaultLog`, so that below in line 128 you can just write `fault_log: self.fault_log.map(f_fail2fail)`—and actually I'd rename the latter to `f_fault`.
`Fault::map` would just return `Fault { node_id: self.node_id, kind: f_fault(self.kind) }`.
* Wherever the code currently says something like
```rust
step.extend_with(other_step, |flt| Fault::new(flt.node_id, f(flt.kind)), to_msg);
```
it should be changed to just:
```rust
step.extend_with(other_step, f, to_msg);
```

File: src/subset/proposal_state.rs [hunk 6]
```diff
@@ -5,7 +5,7 @@ use super::subset::BaSessionId;
 use super::{Error, FaultKind, MessageContent, Result};
 use crate::binary_agreement;
 use crate::broadcast::{self, Broadcast};
-use crate::fault_log::Fault;
+//use crate::fault_log::Fault;
```
Comment (afck) [inline src/subset/proposal_state.rs]: Please remove this if it's not needed.

File: src/dynamic_honey_badger/dynamic_honey_badger.rs [hunk 7]
```diff
@@ -312,9 +312,7 @@ where
         rng: &mut R,
     ) -> Result<Step<C, N>> {
         let mut step: Step<C, N> = Step::default();
-        let to_fault = |hb_fault: Fault<N, honey_badger::FaultKind>| {
-            Fault::new(hb_fault.node_id, FaultKind::HbFault(hb_fault.kind))
-        };
+        let to_fault = |hb_fault: honey_badger::FaultKind| FaultKind::HbFault(hb_fault);
```
Comment (afck) [inline src/dynamic_honey_badger/dynamic_honey_badger.rs]: This could also be replaced with `FaultKind::HbFault`.

File: src/honey_badger/epoch_state.rs [hunk 8]
```diff
@@ -306,9 +306,7 @@ where
     /// Checks whether the subset has output, and if it does, sends out our decryption shares.
     fn process_subset(&mut self, cs_step: CsStep<N>) -> Result<Step<C, N>> {
         let mut step = Step::default();
-        let to_fault = |cs_fault: Fault<N, cs::FaultKind>| {
-            Fault::new(cs_fault.node_id, FaultKind::SubsetFault(cs_fault.kind))
-        };
+        let to_fault = |cs_fault: cs::FaultKind| FaultKind::SubsetFault(cs_fault);
```
Comment (afck) [inline src/honey_badger/epoch_state.rs]: …and this with `FaultKind::SubsetFault`.
