### PR TITLE
An adversary sending faulty decryption shares

### LINKED ISSUE #75: Test filtering out decryption shares that fail verification
In #68, a decryption share received by `HoneyBadger` is verified as soon as the ciphertext becomes available for the proposer of this share's value.

We need a CI test to verify this implementation.

### PR DESCRIPTION
**Pull request by vkomenda**
Close #75

### CODE REVIEW

File: tests/honey_badger.rs [hunk 1]
```diff
@@ -9,15 +10,110 @@ extern crate rand;
...
-use hbbft::messaging::NetworkInfo;
+use hbbft::honey_badger::{self, HoneyBadger, MessageContent};
+use hbbft::messaging::{NetworkInfo, Target, TargetedMessage};
 
-use network::{Adversary, MessageScheduler, NodeUid, SilentAdversary, TestNetwork, TestNode};
+use network::{
+    Adversary, MessageScheduler, MessageWithSender, NodeUid, SilentAdversary, TestNetwork, TestNode,
+};
+
+/// An adversary whose nodes never send any messages.
```
Comment (afck) [inline tests/honey_badger.rs]: The comments are out of date (also below).

File: tests/honey_badger.rs [hunk 2]
```diff
@@ -9,15 +10,110 @@ extern crate rand;
...
+                self.share_triggers.entry(epoch).or_insert(true);
+            }
+        }
+    }
+
+    fn step(&mut self) -> Vec<MessageWithSender<HoneyBadger<usize, NodeUid>>> {
+        let mut outgoing = vec![];
+        let fake_proposal = &Vec::from("X marks the spot");
+
+        for (epoch, mut trigger_set) in &mut self.share_triggers {
```
Comment (afck) [inline tests/honey_badger.rs]: Probably `trigger_set` doesn't need to be mutable: It's already `&mut` — no need to make it `mut &mut`.
